### ISSUE TITLE
code review

### ISSUE THREAD

**Issue by ZabihullahNooriWardak** [jovasal/Capstone#2]
hey jovasal we are morning session :
great job so forth but you speaker section has a little difference with figma design you should work on that .

**Comment by jovasal** [comment]
Ill do that now.

Thank you so much!!

**Comment by jovasal** [comment]
Now is fixed.

![image](https://github.com/jovasal/Capstone/assets/35693330/4d47832a-2b9a-44e8-ba75-11cdca9010d8)

I can continue with my activities.

Thank you so much!
